name: Bug Report
description: Something isn't working as expected? Just report your bug here.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        # Hello there ☺️

        Thanks for taking the time to report a bug. Please fill out the following form to help us fix your issue as soon as possible.

  - type: checkboxes
    attributes:
      label: Preliminary Checks
      description: Please make sure that you verify each checkbox and follow the instructions for them.
      options:
        - label: "This issue is not a duplicate."
          required: true
        - label: "The bug is reproducible."
          required: true
  - type: textarea
    attributes:
      label: Description
      description: Describe the bug that you're encountering.
      placeholder: Be as precise as you can. Feel free to share screenshots, videos, or data from the devtools of your browser.
    validations:
      required: true
  - type: input
    id: reproduction-link
    attributes:
      label: Reproduction Link
      placeholder: "https://github.com/your-name/your-repo/"
      description: |
        Please provide a link to a repository on GitHub that contains a reproduction of your issue.
        You can also provide your link via a [CodeSandbox](https://codesandbox.io/), [CodePen](https://codepen.io/) or [StackBlitz](https://stackblitz.com/).

    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the bug.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Result
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Result
      description: Describe what actually happened.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Environment
      description: In which environment are you using telemetrydeck-react?
      options:
        - React (Browser)
        - Expo
        - React Native
        - Other
    validations:
      required: true
  - type: input
    id: framework
    attributes:
       label: Framework
       description: Are you using a specific framework?
       placeholder: Next.js, Gatsby, etc.
    validations:
      required: false
  - type: input
    id: version
    attributes:
       label: Version
       description: Which version are you using?
       placeholder: 0.2.0
    validations:
      required: false
